// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaG-q8gkiW_hdNGjBnvB7t4moztQ2nk7s',
    appId: '1:64002606720:web:695f1a7710a20a92264865',
    messagingSenderId: '64002606720',
    projectId: 'smarthomeapp-ed852',
    authDomain: 'smarthomeapp-ed852.firebaseapp.com',
    storageBucket: 'smarthomeapp-ed852.firebasestorage.app',
    measurementId: 'G-SVPCM6275K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8oEKOfusGxftOh4UnNzNTa07GsI8CIQo',
    appId: '1:64002606720:android:14b9e0b795218f21264865',
    messagingSenderId: '64002606720',
    projectId: 'smarthomeapp-ed852',
    storageBucket: 'smarthomeapp-ed852.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa8kh_mzlj9x2-JMSjQnhyip5YLBlms8U',
    appId: '1:64002606720:ios:7c268e1010e4e899264865',
    messagingSenderId: '64002606720',
    projectId: 'smarthomeapp-ed852',
    storageBucket: 'smarthomeapp-ed852.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa8kh_mzlj9x2-JMSjQnhyip5YLBlms8U',
    appId: '1:64002606720:ios:7c268e1010e4e899264865',
    messagingSenderId: '64002606720',
    projectId: 'smarthomeapp-ed852',
    storageBucket: 'smarthomeapp-ed852.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaG-q8gkiW_hdNGjBnvB7t4moztQ2nk7s',
    appId: '1:64002606720:web:e4143b1b7f7e11ea264865',
    messagingSenderId: '64002606720',
    projectId: 'smarthomeapp-ed852',
    authDomain: 'smarthomeapp-ed852.firebaseapp.com',
    storageBucket: 'smarthomeapp-ed852.firebasestorage.app',
    measurementId: 'G-ZF3Y7ZRPWM',
  );
}
